### ISSUE TITLE
3dsmaxで作成したabcファイルの読み込みについて　import abc made by 3ds max 

### ISSUE THREAD

**Issue by than19** [Unity-Technologies/AlembicForUnity#143]
昨日ご連絡させて頂いた者です。
添付の画像が示すような流体シミュレーションを3dsmaxで行いました。

3dsmaxでABCファイルを書き出し。ファイル形式はOgawaです。
Alembic for UnityをカスタムパッケージとしてUnityにインポート。全てにチェックを入れました。
Assets直下にabcをインポート致しました。

しかし、肝心の流体のみが読み込まれず、簡易的に作成した水路のみが反映され、prefabではなく単なるファイルとして認識されております。
fbxとは違いabcであればこの流体のシミュレーションも読み込めるはずなのですが、、、、
些細なことですが傾いて読み込まれるのも原因不明です。
バージョンは最新版(2018.1.6f1)64bitです。

下記を添付致します。
unityの画面
abcファイル
3dsmaxの画面

3dsmaxのファイルの添付はサポートされていないようなので、必要であれば何らかの方法でお送り致します。
よろしくお願い致します。

[Editor.log](https://github.com/unity3d-jp/AlembicForUnity/files/2144031/Editor.log)
![3dsmax](https://user-images.githubusercontent.com/40654412/42016780-c0691718-7ae7-11e8-8f64-12106f2f739b.PNG)
![errorunity](https://user-images.githubusercontent.com/40654412/42016783-c39c0d32-7ae7-11e8-89b9-e2af73d1e97d.PNG)

**Comment by i-saint** [comment]
別ルートで頂いた .abc と .max ファイル:
https://drive.google.com/drive/folders/1aMuUTDkNYU9TVXsefIy0WYYx1Chk0pHI

**Comment by i-saint** [comment]
ノード名に日本語が含まれているのが原因である疑いがあります。英数字の名前にリネームして .abc にエクスポートしてそれが正しく読めるか確認していただけますでしょうか。
(私の環境で Max でエクスポートしても日本語ノード名が一致せず、再現できません)

**Comment by i-saint** [comment]
本件で初めて知ったんですが、Alembic はファイルの仕様的に日本語 (を含むマルチバイト文字) を正しく扱えないそうです。日本語がクラッシュの原因かはまだはっきりしませんが、いずれにせよ対策は近い先に入れようと思います。
(Maya はちゃんと対策しているようで、頂いた .abc ファイルを Maya で読むと、元は "Solver01.重力001" だったのが "Solver01__d_Í001" のようにリネームされます)

**Comment by i-saint** [comment]
手元で日本語ノード名のリネーム処理を入れたら問題の .abc ファイルも正常にインポートできるようになったので、日本語ノード名が原因なのはほぼ確定。
この修正は次のリリースに入れますが、今は Max 側でリネームして回避していただければと思います。

**Comment by hiroki-o** [comment]
Translation Memo:
This is an issue introduced by Japanese node name on 3dsMax. Alembic does not handle Japanese node name correctly by design so it must be renamed.

Seiya comment:
- Workaround will go into next release but for those experiencing this issue, please rename your node in 3dsmax.

**Comment by clusty** [comment]
Please reopen if still not fixed in the latest version.
