### ISSUE TITLE
Alembic object may disappear from SceneView depends on camera angle or distance

### ISSUE THREAD

**Issue by pepoipod** [Unity-Technologies/AlembicForUnity#187]
はじめまして、AlembicForUnityを使って開発させていただいているものです。

## 発生している現象
AlembicForUnityを介して読み込んだAlembicのオブジェクトについて、以下のような現象が発生します。

*  SceneViewでAlembicのオブジェクトに寄ると、Alembicのオブジェクトが画面から消える。が、その反対に回り込んでオブジェクトに寄ると、Alembicのオブジェクトは画面から消えない。
* SceneViewでAlembicのオブジェクトを上から覗き込んだり下から覗き込んだりすると、Alembicのオブジェクトが画面から消える。
* 上記と同様の現象がGameViewでも発生します。

### Sceneビューで遠くから対象を見ている時
<img width="770" alt="2018-08-20 18 02 01" src="https://user-images.githubusercontent.com/9960464/44331573-cdd9e080-a4a4-11e8-87a9-4e0061cc2ee6.png">

### Sceneビューで近くから対象を見ている時
<img width="769" alt="2018-08-20 18 02 05" src="https://user-images.githubusercontent.com/9960464/44331578-d3cfc180-a4a4-11e8-8c95-18c1a4ff97a6.png">

### 動画
[https://gyazo.com/6d3141b7d0b77110aba4c468b430120c](https://gyazo.com/6d3141b7d0b77110aba4c468b430120c)

## 補足情報
対象のabcファイル（サイズが大きいので、firestorageにアップいたしました）
[http://xfs.jp/1gHk1M](http://xfs.jp/1gHk1M)

パッケージバージョン
20180413

[Editor.log.zip](https://github.com/unity3d-jp/AlembicForUnity/files/2301809/Editor.log.zip)

以上、よろしくお願いいたします。

**Comment by i-saint** [comment]
情報ありがとうございます。
Windows では再現しなかったので、Mac 限定の問題かもしれず、対応に時間がかかるかもしれません。

**Comment by pepoipod** [comment]
ありがとうございます。
何卒よろしくお願いいたします。

**Comment by hiroki-o** [comment]
Translation Memo of this issue:
* Alembic object disappears when camera get close to it on SceneView (and GameView too) from one side. Getting close from other side does not make object disappears.

* Alembic object disappears when you look at from bottom or above in SceneView (and GameView too).

Seiya(i-saint) Comment:
- didn't get reproduced on Windows, could be Mac only issue.

**Comment by cguer** [comment]
Hello, we are closing this issue as we are currently unable to reproduce the problem with recent versions of the Alembic package. Please feel free to re-open with details if you are still having this issue.
