### ISSUE TITLE
Surface and Particle on Alembic has gap on playback

### ISSUE THREAD

**Issue by toshinoritakata** [Unity-Technologies/AlembicForUnity#203]
### 発生している問題
SurfaceとParticleのAlembicファイルを同時に再生すると表示がずれてしまうようです。

### 試してみたこと
自作のプロプラムでSurfaceとParticleのAlembicファイルを別に作成し、
Alembic For Unityで同じタイムラインに載せて再生した所、表示がずれてしまいました。
Houdiniで確認すると問題なく同期再生されたので、念の為Houdiniでマージした
Alembicファイルを書き出しUnityで表示させてみましたが改善されませんでした。

### 検証ムービー
https://drive.google.com/open?id=1a2K2wrhTRb9JBEoOITfn80KXl-FV6lwH

### 検証データ(Unityプロジェクトデータ一式)
https://drive.google.com/open?id=1LyzoC_1H_2buJPk-IETPGKbQ3pt2VgOk

### 問題が起こっている環境
- Unity: Unity 2018.2.11f1 
- OS: Windows10
- Graphics board: NVIDIA GTX1080 x2 (SLIなし)
- AlembicファイルはSSDから読み込んでいます

ウィンドウのサイズを変更すると一致するのでアップデートのタイミングに
問題が有るように思いますが、ご確認いただけますでしょうか？
よろしくお願いいたします。

**Comment by hiroki-o** [comment]
Translation Memo:
Surface and Particle on Alembic has gap on playback.

**Comment by clusty** [comment]
File links seem to be broken.
Will close for now.  If this is still an issue please reopen with a new link to the files

**Comment by cguer** [comment]
Hello, we are closing this issue as we are unable to reproduce it with the current version of the Recorder package (2.2.0-pre.3). Please free free to re-open with more details if you are still experiencing this problem.
