### ISSUE TITLE
Alembic cache for android

### ISSUE THREAD

**Issue by lkdgroot** [Unity-Technologies/AlembicForUnity#308]
Hi, we 've recently started using Alembic cache for an Android AR application.
Using     "com.unity.formats.alembic": "1.0.6"
I've read that alembic cache does not work at all with Android.
Is this still the case, or is there a possible workaround?

Luckily enough we would currently only have to switch out 1 animation.
But we would prefer to keep using Alembic cache if at all possible.

**Comment by clusty** [comment]
Hey,
The heavy lifting for the alembic playback is done by the native libalembic.
Unfortunately if you wanted to add a new platform, you'd have to compile that for that platform.
I am not familiar with the android toolchain so I can't judge how hard it would be to support.

**Comment by clusty** [comment]
Closing for now
