### ISSUE TITLE
Import Points Crashes & Incorrect Behaviour in URP

### ISSUE THREAD

**Issue by aarondemolder** [Unity-Technologies/AlembicForUnity#335]
- abc file is 1.5gb, points only, exported from Houdini and contains 400 frames, link valid for a week - https://we.tl/t-xH1PtFbjPn
- using version 1.0.6 in 2019.3.15f1
- Editor.log Attached
[Editor-prev.log](https://github.com/Unity-Technologies/AlembicForUnity/files/4716921/Editor-prev.log)

Can provide full project if required.

**Point Crashes:**

When loading in an alembic that contains only points, without changing the import settings to exclude both Swap Handedness and Interpolate Samples I get a crash (log attached)

**Incorrect Behaviour in URP:**

When using the Alembic Points Renderer with the Built-In Render Pipeline I get the correct behaviour of all my points being visible in the correct positions and the mesh is correctly instanced across them. But when in URP I only receive a single point along the origin (or maybe all points are in one position). It also seems to ignore changes to Point Size. Happens on any given mesh. Materials can still be correctly applied though.

Built In Pipeline:
![builtinpipeline](https://user-images.githubusercontent.com/25490210/83516613-53d6e800-a4cf-11ea-8d9e-d2ae3ecdf48c.png)

URP:
![URP](https://user-images.githubusercontent.com/25490210/83516615-546f7e80-a4cf-11ea-8702-e18721964a38.png)

Let me know if you need any other info or files!

**Comment by aarondemolder** [comment]
I also wanted to add that by default it would be nice for the instancer to use the point colour from the loaded file for the alembic shaders. Here I use Cd vertex colour.

**Comment by clusty** [comment]
> I also wanted to add that by default it would be nice for the instancer to use the point colour from the loaded file for the alembic shaders. Here I use Cd vertex colour.

Hey,
Seems your bug report slipped through the cracks. Sorry about that.
Mind reposting the file ?

**Comment by clusty** [comment]
Please reopen if still important to fix.
Missing the asset to repro for now.

**Comment by sambeebe** [comment]
I'm having basically the exact same issue, not just in URP but regular and HDRP as well.

**Comment by clusty** [comment]
> I'm having basically the exact same issue, not just in URP but regular and HDRP as well.

Mind sending me an asset that repros the problem? I’d be more than happy to look at it.

**Comment by sambeebe** [comment]
thanks for the quick reply, here's an alembic containing only points (from houdini, if that matters): https://we.tl/t-4wIdwVrbym. Immediately crashes Unity when you try to load it in any version I've tried (most recently 2019.4.18f1) regardless of whether you check "import points".

**Comment by aarondemolder** [comment]
@sambeebe reopening this has prompted me to dig out the alembic file I was having this issue with!

available - https://drive.google.com/drive/folders/1zgiPSHz7gcD0HH-kR4hnWdCgug06lz4v?usp=sharing

also exported from houdini, with colour data as cd

![Screenshot from 2021-03-26 19-13-44](https://user-images.githubusercontent.com/25490210/112682037-7293da00-8e67-11eb-85ec-e75532515a62.png)

**Comment by clusty** [comment]
> @sambeebe reopening this has prompted me to dig out the alembic file I was having this issue with!
> 
> available - https://drive.google.com/drive/folders/1zgiPSHz7gcD0HH-kR4hnWdCgug06lz4v?usp=sharing
> 
> also exported from houdini, with colour data as cd
> 
> ![Screenshot from 2021-03-26 19-13-44](https://user-images.githubusercontent.com/25490210/112682037-7293da00-8e67-11eb-85ec-e75532515a62.png)

Thanks for the assets fellas.
I loaded both files with Alembic 2.1.3 and 2.2.0-exp.2 and they both load fine on OSX:
Mind trying it with one of these versions ? The exp version needs 2019.4 as minimum version (2.1.3 works with 2019.3)
<img width="1633" alt="Screen Shot 2021-03-26 at 3 43 37 PM" src="https://user-images.githubusercontent.com/328523/112685058-63eafa00-8e4a-11eb-9058-a941e13c4200.png">
If you are still crashing, I will need to know the OS / Alembic package version.

**Comment by sambeebe** [comment]
D'oh.. I was using an older version, didn't see there was a newer version. Thank you very much!

PS-- while I'm here, I'll second aaron's suggestion to load color attributes (@Cd in Houdini) automatically :)

**Comment by clusty** [comment]
> D'oh.. I was using an older version, didn't see there was a newer version. Thank you very much!
Thanks. 
Colour was added for meshes since there was a widespread ask for it. Even that proved to be quite a headache because it's not in the base schema, and every dcc decided on a different name and data type for colour.
Adding yet another custom attribute to the list is not sustainable.
I'll have to figure out a way to read them all :)
I suggest you head to the forum if you want to talk about alembic features.

Will re-close the issue again.
