### ISSUE TITLE
Public Script API access to AlembicExporter

### ISSUE THREAD

**Issue by m1keall1son** [Unity-Technologies/AlembicForUnity#360]
This is a feature request to enable public access the AlembicExporter so I can set the output path, adjust settings and trigger recordings from runtime scripts.  Thanks!

**Comment by clusty** [comment]
Hey,
I presume you are using alembic 1.0.X ?
Could you please update to alembic 2.X and test if there are missing APIs ?
You should be able to do things like:
`    public class Blah : UnityEngine.MonoBehaviour
    {
        void Update()
        {
            var exp = gameObject.GetComponent<AlembicExporter>();
            exp.Recorder.Settings.OutputPath = "ABCD"
        }
    }`

**Comment by m1keall1son** [comment]
🤦‍♂️ Apologies, I had the wrong version and had not checked for an update, all the parts of the API I need are present, thank you!!
