### ISSUE TITLE
Namespace Cloth could not be found

### ISSUE THREAD

**Issue by melMass** [Unity-Technologies/AlembicForUnity#367]
Hi,

I have a strange error and I don't know what could be the cause, it's complaining about a default Unity namespace missing, Cloth...:

```ruby
Library/PackageCache/com.unity.formats.alembic@2.1.0-preview.3/Runtime/Scripts/Exporter/AlembicExporter_impl.cs(681,13): error CS0246: The type or namespace name 'Cloth' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by clusty** [comment]
Did you disable by chance ` "com.unity.modules.cloth": "1.0.0",` from your project's manifest ?

**Comment by melMass** [comment]
That was it thanks
