### ISSUE TITLE
Platform defines for abci.bundle include iOS for x86_64 library.

### ISSUE THREAD

**Issue by AdamFrisby** [Unity-Technologies/AlembicForUnity#375]
Hi there - 

A simple fix/request - 

abci.bundle is not specified as macOS-only, and will export into an iOS project, breaking the build. Please mark the library as macOS only. (This also may apply to the .so for Linux & Android)

EDIT: Unity 2018.4.20f / Alembic 1.0.7

**Comment by clusty** [comment]
Hello,

Thanks a lot for the bug report. I reproduced it and will submit a fix https://github.com/Unity-Technologies/AlembicForUnity/pull/376

**Comment by clusty** [comment]
Fix was QAed and merged.
