### ISSUE TITLE
DllNotFoundException and alembic not animating in Oculus Quest 2

### ISSUE THREAD

**Issue by dioptre** [Unity-Technologies/AlembicForUnity#401]
I've added an alembic file to my project in unity, and everything works in the local player. I initially got "Colliding plugins on Unity build" error like in  https://github.com/Unity-Technologies/AlembicForUnity/issues/72 . I excluded either the x64 or 32 bit versions when I target the Oculus Quest 2. The animation doesn't start (though I can see the 1st frame - it just doesn't animate) and I get the following log:

```
01-22 16:11:40.161  9407  9428 E Unity   : DllNotFoundException: abci
01-22 16:11:40.161  9407  9428 E Unity   :   at (wrapper managed-to-native) UTJ.Alembic.aiContext.aiContextCreate(int)
01-22 16:11:40.161  9407  9428 E Unity   :   at UTJ.Alembic.aiContext.Create (System.Int32 uid) [0x00000] in <ffb92e91ae0049e0b64cffe65f7beac7>:0 
01-22 16:11:40.161  9407  9428 E Unity   :   at UTJ.Alembic.AlembicStream.AbcLoad (System.Boolean createMissingNodes) [0x00020] in <ffb92e91ae0049e0b64cffe65f7beac7>:0 
01-22 16:11:40.161  9407  9428 E Unity   :   at UTJ.Alembic.AlembicStreamPlayer.LoadStream (System.Boolean createMissingNodes) [0x00026] in <ffb92e91ae0049e0b64cffe65f7beac7>:0 
01-22 16:11:40.161  9407  9428 E Unity   :   at UTJ.Alembic.AlembicStreamPlayer.Update () [0x0009d] in <ffb92e91ae0049e0b64cffe65f7beac7>:0 
01-22 16:11:40.161  9407  9428 E Unity   :   at UTJ.Alembic.AlembicStreamPlayer.LateUpdate () [0x00016] in <ffb92e91ae0049e0b64cffe65f7beac7>:0 
```
@psytron

**Comment by psytron** [comment]
The original error when importing standard Alembic file:

Found plugins with same names, Assets/UTJ/Alembic/Plugins/x86_64/abci.dll and Assets/UTJ/Alembic/Plugins/x86/abci.dll. Delete the one of the duplicate plugins.
UnityEditor.AndroidPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at /Users/bokken/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)

**Comment by clusty** [comment]
> I've added an alembic file to my project in unity, and everything works in the local player. I initially got "Colliding plugins on Unity build" error like in #72 . I excluded either the x64 or 32 bit versions when I target the Oculus Quest 2. The animation doesn't start (though I can see the 1st frame - it just doesn't animate) and I get the following log:
> 
> ```
> 01-22 16:11:40.161  9407  9428 E Unity   : DllNotFoundException: abci
> 01-22 16:11:40.161  9407  9428 E Unity   :   at (wrapper managed-to-native) UTJ.Alembic.aiContext.aiContextCreate(int)
> 01-22 16:11:40.161  9407  9428 E Unity   :   at UTJ.Alembic.aiContext.Create (System.Int32 uid) [0x00000] in <ffb92e91ae0049e0b64cffe65f7beac7>:0 
> 01-22 16:11:40.161  9407  9428 E Unity   :   at UTJ.Alembic.AlembicStream.AbcLoad (System.Boolean createMissingNodes) [0x00020] in <ffb92e91ae0049e0b64cffe65f7beac7>:0 
> 01-22 16:11:40.161  9407  9428 E Unity   :   at UTJ.Alembic.AlembicStreamPlayer.LoadStream (System.Boolean createMissingNodes) [0x00026] in <ffb92e91ae0049e0b64cffe65f7beac7>:0 
> 01-22 16:11:40.161  9407  9428 E Unity   :   at UTJ.Alembic.AlembicStreamPlayer.Update () [0x0009d] in <ffb92e91ae0049e0b64cffe65f7beac7>:0 
> 01-22 16:11:40.161  9407  9428 E Unity   :   at UTJ.Alembic.AlembicStreamPlayer.LateUpdate () [0x00016] in <ffb92e91ae0049e0b64cffe65f7beac7>:0 
> ```
> 
> @psytron

Hey,
Unless In am mistaking, Occulus Quest is based on Android, which is not supported by the Alembic package unfortunately. I think in version 2.0, you get build time errors to this effect.
 
> The original error when importing standard Alembic file:
> 
> Found plugins with same names, Assets/UTJ/Alembic/Plugins/x86_64/abci.dll and Assets/UTJ/Alembic/Plugins/x86/abci.dll. Delete the one of the duplicate plugins.
> UnityEditor.AndroidPluginImporterExtension:CheckFileCollisions(String)
> UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at /Users/bokken/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)

Yeah, that's the old version of the package, that's obsolete. You can safely delete.
